safe:        false
auto:        true
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

paginate: 5
pagination: true
searchindex: yes

articles_title: "Articles"
articles_header: "Previous posts"

my_project:
  projecta:
    title: Project A
    image: /img/projecta.jpg
    description: This is project A. The image wont work.

  projectb:
    title: Project B
    image: /img/projectb.jpg
    description: This is project B. The image wont work.

  projectc:
    title: Project C
    image: /img/projectc.jpg
    description: This is project C. The image wont work.